"""Initial migration.

Revision ID: 989e4283cb15
Revises: 
Create Date: 2024-11-07 22:53:50.428794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989e4283cb15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('palette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colors', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palette')
    op.drop_table('user')
    # ### end Alembic commands ###
